# Generated by Django 3.2.4 on 2021-07-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Face',
        ),
    ]
