# Generated by Django 3.2.4 on 2021-07-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'undefine'), (1, 'man'), (2, 'woman')], default=0)),
            ],
        ),
    ]
