# Generated by Django 3.2.4 on 2021-07-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accounts'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='filename',
            field=models.FileField(upload_to=''),
        ),
    ]
